Version 4
SymbolType CELL
RECTANGLE Normal -96 -64 96 64
WINDOW 0 0 -80 Center 0
WINDOW 3 0 -43 Center 0
SYMATTR Prefix X
SYMATTR Description Universal Voltage Regulator
SYMATTR Value NAME
PIN -96 0 LEFT 8
PINATTR PinName IN
PINATTR SpiceOrder 1
PIN 0 64 BOTTOM 8
PINATTR PinName ADJ
PINATTR SpiceOrder 2
PIN 96 0 RIGHT 8
PINATTR PinName OUT
PINATTR SpiceOrder 3
